const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const root=path.resolve(__dirname,'../docs');
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,b)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.json':'application/json'})[path.extname(file)]||'text/plain');res.end(b);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});try{const page=await browser.newPage({viewport:{width:1280,height:1000},colorScheme:'dark'}),errors=[];page.on('pageerror',e=>errors.push(e.message));const vocabulary=JSON.parse(fs.readFileSync(path.join(root,'data/words.json'),'utf8')).items;
await page.route('https://*/rest/v1/**',route=>{const u=new URL(route.request().url());let data;if(u.pathname.endsWith('/words')){const off=Number(u.searchParams.get('offset'));data=vocabulary.slice(off,off+1000);}else if(u.pathname.endsWith('/speaking_events'))data=[{id:'test1',speaker:'Medi',word_key:'ana ba7ki',lesson_date:'2026-09-15',t_start:40,text:'ba7ki',assessment:'independent',row_id:'r1'},{id:'test2',speaker:'Amal',word_key:'ana ba7ki',lesson_date:'2026-09-16',t_start:80,text:'ba7ki',assessment:'unresolved',row_id:'r2'}].slice(Number(u.searchParams.get('offset')||0)).map(e=>({data:e}));else if(u.pathname.endsWith('/speaking_release'))data=[{data:{revision:'test'}}];else if(u.pathname.endsWith('/card_results'))data=[];else data=[];return route.fulfill({json:data,headers:u.pathname.endsWith('/speaking_events')?{'content-range':'0-1/2'}:{}});});
await page.goto('http://127.0.0.1:'+server.address().port+'/word-bank.html');await page.waitForFunction(()=>window.AneesWordBankPage?.rows.length>0);
const total=await page.locator('#ab-allcount').innerText();assert(Number(total)>1500);assert.equal(await page.locator('[aria-expanded="true"]').count(),0);
await page.locator('#ab-search').fill('ba7ki');await page.locator('[data-open="ana ba7ki"]').click();assert.equal(await page.locator('.ab-form').count(),4);assert.equal(await page.locator('.ab-use').count(),0);assert.equal(await page.locator('.ab-personrow').count(),27);assert.equal(await page.locator('.ab-status-Good').count()>0,true);
await page.locator('#ab-search').fill('badfa3');await page.locator('[data-open="ana badfa3"]').click();assert.equal(await page.locator('.ab-use').count(),4);
await page.locator('#ab-search').fill('baarda');assert.equal(await page.locator('.ab-row').count(),1);assert.match(await page.locator('.ab-wordbutton').innerText(),/Baared \/ Baarda/s);await page.locator('[data-open="bAred"]').click();assert.equal(await page.locator('.ab-personrow').count(),0);assert.equal(await page.locator('.ab-personlist details').count(),0);
await page.locator('#ab-search').fill('Mabsoo6');assert.match(await page.locator('.ab-wordbutton').first().innerText(),/Mabsoo6a/);assert.match(await page.locator('.ab-wordbutton').first().innerText(),/Mabsoo6een/);
await page.locator('#ab-reset').click();await page.locator('#ab-usage').selectOption('partial');assert.equal(await page.locator('.ab-row').count(),1);
await page.locator('#ab-reset').click();await page.locator('#ab-search').fill('<script>alert(1)</script>');assert.equal(await page.locator('.ab-row').count(),0);
await page.locator('#ab-reset').click();await page.screenshot({path:path.resolve(__dirname,'../../word-bank-desktop.png'),fullPage:false});
for(const width of [320,375,768,1024]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'overflow at '+width);}
await page.screenshot({path:path.resolve(__dirname,'../../word-bank-mobile.png'),fullPage:false});
assert.deepEqual(errors,[]);console.log(JSON.stringify({total,rows:vocabulary.length,browserErrors:errors,checks:'search, source data, 27 Ba7ki forms, lexical uses, filters, XSS escaping, four viewport widths'},null,2));
// Network failure must retain vocabulary and not fabricate scoring.
await page.unroute('https://*/rest/v1/**');await page.route('https://*/rest/v1/**',r=>r.abort());await page.reload();await page.waitForFunction(()=>window.AneesWordBankPage?.rows.length>0);assert.match(await page.locator('#ab-notice').innerText(),/cached|Saved/);
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
