/* Audit the published learner ledger without modifying its raw source. Usage: node scripts/audit_word_bank_reliability.cjs path/to/snapshot.json [baseline-events.json] */
const fs=require('fs'),path=require('path'),crypto=require('crypto'),root=path.resolve(__dirname,'..'),C=require('../docs/js/word-bank-core.js'),R=require('../docs/js/word-bank-review.js'),T=require('../docs/js/word-bank-context.js');
const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,'')),hash=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');
const snap=read(process.argv[2]),raw=snap.events||snap,baseline=process.argv[3]?read(process.argv[3]):raw,review=read(root+'/docs/data/word-bank-review.json'),applied=R.apply(raw,review);if(applied.stale.length)throw Error('Stale source guards: '+applied.stale.join(','));
const ev=C.prepareEvidence(applied.events),learners=ev.filter(e=>e.speaker==='Medi'),clips=read(root+'/docs/data/word-bank-clips.json').clips,words=read(root+'/docs/data/words.json').items,keys=new Set(words.map(w=>w.key)),catalog=read(root+'/docs/data/word-bank-catalog.json'),models=C.models(words,catalog,ev,[]);
const pending=e=>C.points(e)===null&&!e.ignored&&!e.immediate_repeat&&!e.is_echo&&!e.grammar_only&&!e.observation_only&&!e.scored_in_event;
const originalPending=new Set(baseline.filter(e=>e.speaker==='Medi'&&pending(e)).map(e=>e.id)),counts={},problems=[];
const sourceRows=new Map();for(const e of ev){if(!sourceRows.has(e.lesson_date))sourceRows.set(e.lesson_date,new Map());for(const r of e.context||[])sourceRows.get(e.lesson_date).set(r.row_id,r);}
const ledger=learners.map(e=>{
 const score=C.points(e),turn=T.ownTurn(e),clip=clips[e.id],parts=e[score===0?'wrong_parts':score===.5?'partial_parts':'correct_parts']||[e.text],text=turn?.rows.map(r=>r.reviewed_arabizi||T.text(r)).join(' ')||e.text;
 // Pass 1: stable identity, source timing and full-turn coverage.
 const source={guard:!applied.stale.includes(e.id),fingerprint:!!e.source_sha256,row_found:!!turn,timing:Number.isFinite(e.t_start)&&Number.isFinite(e.t_end)&&e.t_end>=e.t_start,catalog:!e.word_key||keys.has(e.word_key)};
 // Pass 2: exclusions, duplicates and scored-form attribution across the complete catalog.
 const rules={excluded_not_scored:!(e.ignored||e.is_echo||e.immediate_repeat||e.grammar_only||e.scored_in_event)||score===null,pending_not_scored:!e.needs_review||score===null,form_attributed:score===null||models.some(r=>r.entries.some(f=>f.speaking.attempts.some(a=>a.id===e.id)))};
 // Pass 3: highlighted target and source-bound playable file covering the displayed context.
 const presentation={highlight:score===null||e.spoken===false||parts.length===0||R.mark(text,parts).includes('<mark'),audio:!!clip&&clip.source_sha256===e.source_sha256&&clip.lesson===e.lesson_date&&clip.start<=e.t_start&&clip.end>=e.t_end&&fs.existsSync(root+'/docs/'+clip.sentence_audio_url),context_in_clip:!!clip&&(e.context||[]).every(r=>r.timeline_start>=clip.start&&r.timeline_end<=clip.end),grouping_lossless:T.turns(e.context).flatMap(t=>t.rows).length===new Set((e.context||[]).filter(r=>T.text(r).trim()).map(r=>r.row_id)).size};
 for(const [pass,checks] of Object.entries({source,rules,presentation}))for(const [name,ok]of Object.entries(checks))if(!ok&&!(name==='row_found'&&score===null))problems.push({id:e.id,pass,check:name});
 const status=score===1?'Correct':score===.5?'Partial':score===0?'Wrong':pending(e)?'Needs review':'Not scored';counts[status]=(counts[status]||0)+1;
 const extra=originalPending.has(e.id)||pending(e)?(()=>{const broader=[...sourceRows.get(e.lesson_date).values()].filter(r=>r.timeline_start>=e.t_start-45&&r.timeline_start<=e.t_end+45).sort((a,b)=>a.timeline_start-b.timeline_start);return {pass4:{method:'wider available source context',rows:broader.length,context_sha256:hash(broader)},pass5:{method:'catalog identity and alternative transcript check',catalog_candidates:e.candidate_keys||[],transcript_status:e.wording_status,raw_source_preserved:true},pass6:{method:'final counterexample check: repetition, grammar, prompt versus supplied answer, self-correction, false ASR binding',outcome:status,remaining_reason:pending(e)?e.reason:null}};})():undefined;
 return {id:e.id,word:e.word_key,date:e.lesson_date,time:e.t_start,source_sha256:e.source_sha256,passes:{source,rules,presentation},extra,status,reason:e.reason};
});
if(problems.length){console.error(JSON.stringify(problems,null,2));process.exitCode=1;}
const events=learners.map(e=>{const p=C.points(e),turn=T.ownTurn(e);return {id:e.id,date:e.lesson_date,time:e.t_start,row_id:e.row_id,word:e.word_key,status:ledger.find(l=>l.id===e.id).status,changed:!!review.patches[e.id]||review.additions.some(a=>a.event.id===e.id),sentence:turn?turn.rows.map(r=>r.reviewed_arabizi||T.text(r)).join(' '):e.text,reason:e.reason,self_corrected:!!e.self_corrected,wrong_parts:p===0?e.wrong_parts||[e.text]:[],audio:clips[e.id]?.sentence_audio_url};});
const summary={version:review.version,scope:`${learners.length} learner occurrences across ${new Set(learners.map(e=>e.lesson_date)).size} published lessons. Three dataset-wide source/rule/presentation checks, plus three additional checks for the original pending set and newly flagged cases. Flagged exchanges were contextually adjudicated; 30 difficult recording excerpts were compared with two transcription models. These are transcript-based assessments, not a claim that every pronunciation was verified by listening. September 14 and 18 are not imported.`,counts,checks:{learner_occurrences:learners.length,initial_pending:originalPending.size,extra_checked:ledger.filter(l=>l.extra).length,integrity_failures:problems.length},events};
fs.writeFileSync(root+'/docs/data/word-bank-audit.json',JSON.stringify(summary,null,2)+'\n');fs.writeFileSync(root+'/docs/data/word-bank-audit-checks.json',JSON.stringify({version:review.version,checks:summary.checks,ledger},null,2)+'\n');console.log(JSON.stringify({counts,checks:summary.checks},null,2));
