# -*- coding: utf-8 -*-
"""PG-37 one box per line (Medi 2026-10-08 "Can we turn this into just 1 box and we can write the correction, not try
and separate into so many boxes?"). The server half of the one box:

  build-prompt   scripts/correction_parse_prompt.md -> supabase/functions/parse-correction/prompt.ts (one source of truth)
  read-notes     every 'note' row (his words the page could not shape, and the AI read was off) gets ONE Claude Haiku
                 read (`claude -p --model claude-haiku-5-5`, the same prompt file), logged like every paid call
                 (scripts/track.py run line with cost; data/budget.json 'anthropic'); the structured rows it yields are
                 inserted into transcript_corrections (payload.raw = his words, payload.parsed_from = the note id) and
                 added to the mirror so this hour's build sees them. A note that yields nothing stays a note (never
                 re-read: payload.parsed_from on a 'note' child marks it done).
  mirror-spend   the edge function's api_spend rows (service anthropic, note 'parse-correction ...') become
                 data/budget.json calls + run lines, so check_rules AI-paid-logged sees every paid call.
  run            read-notes + mirror-spend (what `medi_corrections.py pull` calls; fail-open, never blocks a publish)

Nothing here edits a raw transcript (S2) and nothing asks Amal anything."""
import datetime as dt
import json
import os
import re
import subprocess
import sys
import uuid

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import track  # noqa: E402

PROMPT_P = os.path.join(HERE, "correction_parse_prompt.md")
PROMPT_TS = os.path.join(REPO, "supabase", "functions", "parse-correction", "prompt.ts")
STATE_P = os.path.join(REPO, "data", "lesson-work", "correction-parse-state.json")
MODEL = "claude-haiku-5-5"
CLAUDE = os.environ.get("ANEES_CLAUDE_BIN") or "claude"
MAX_NOTES_PER_RUN = 20


def J(p, default=None):
    if not os.path.exists(p):
        return default
    with open(p, encoding="utf-8-sig") as f:
        return json.load(f)


def W(p, obj):
    os.makedirs(os.path.dirname(p), exist_ok=True)
    tmp = p + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=1)
    os.replace(tmp, p)


def mmss(t):
    t = max(0, int(float(t or 0)))
    return "%d:%02d" % (t // 60, t % 60)


# ------------------------------------------------------------------ the prompt, one source of truth

def prompt_text():
    with open(PROMPT_P, encoding="utf-8") as f:
        return f.read()


def build_prompt_ts(path=PROMPT_TS):
    """prompt.ts for the edge function = the .md verbatim (a test checks they match)."""
    txt = prompt_text()
    body = ("// Generated by `python scripts/correction_parse.py build-prompt` from scripts/correction_parse_prompt.md - do not edit.\n"
            "export const PROMPT = " + json.dumps(txt, ensure_ascii=False) + ";\n")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(body)
    return path


def prompt_ts_fresh(path=PROMPT_TS):
    if not os.path.exists(path):
        return False
    with open(path, encoding="utf-8") as f:
        return json.dumps(prompt_text(), ensure_ascii=False) in f.read()


def fill(who, t, line, text, context=None):
    return (prompt_text().replace("{context}", context or "(not given)").replace("{who}", who).replace("{mmss}", mmss(t))
            .replace("{line}", line or "(empty)").replace("{text}", text))


CTX_BEFORE, CTX_AFTER = 20.0, 40.0          # PR-22: the lines around the one he wrote under (his sentence is often split)


def lesson_turns(date):
    """The lesson's lines as the engine wrote them: [{t, end, who, text}] (the page's overlay undone: engine words)."""
    L = J(os.path.join(REPO, "docs", "data", "lessons", str(date) + ".json"), {}) or {}
    return [{"t": float(u["t"]), "end": u.get("end"), "who": u.get("who"), "text": u.get("engine") or u.get("text") or ""}
            for u in L.get("turns") or [] if u.get("who") in ("Medi", "Amal", "chat")]


def context_lines(note, turns=None):
    """PR-22: the lines from 20 s before to 40 s after the note's line, one per row: '[m:ss Who] text'."""
    t0 = float(note.get("turn_t") or 0)
    t1 = float((note.get("payload") or {}).get("turn_end") or t0)
    turns = lesson_turns(note.get("lesson_date")) if turns is None else turns
    return chr(10).join("[%s %s] %s" % (mmss(u["t"]), "Tutor (chat)" if u["who"] == "chat" else u["who"], u["text"])
                     for u in turns if t0 - CTX_BEFORE <= u["t"] <= t1 + CTX_AFTER)


# ------------------------------------------------------------------ the AI read -> items (checked against the line)

def _norm(s):
    s = re.sub(r"[ً-ْٰـ]", "", str(s or ""))
    s = s.replace("أ", "ا").replace("إ", "ا").replace("آ", "ا").replace("ة", "ه").replace("ى", "ي").lower()
    return re.sub(r"[^\wء-ي]+", "", s)


def _bare(w):
    return re.sub(r"^(?:ال|el[- ]?|al[- ]?|il[- ]?)", "", str(w or ""), flags=re.I)


def _lev(a, b):
    if a == b:
        return 0
    if not a or not b:
        return len(a) or len(b)
    prev = list(range(len(b) + 1))
    for i, ca in enumerate(a, 1):
        cur = [i]
        for j, cb in enumerate(b, 1):
            cur.append(min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + (ca != cb)))
        prev = cur
    return prev[-1]


def _sim(a, b):
    a, b = _norm(a), _norm(b)
    if not a or not b:
        return 0.0
    return 1 - _lev(a, b) / max(len(a), len(b))


def in_line(w, line, floor=0.6):
    """The word of the line that is (or sounds most like) w, 'the' prefixes not counting; None when nothing is close."""
    best, bs = None, floor
    for lw in re.split(r"[\s.…,،؟?!:;\"“”«»()]+", str(line or "")):
        if not lw:
            continue
        s = max(_sim(w, lw), _sim(_bare(w), _bare(lw)))
        if s >= bs:
            bs, best = s, lw
    return best


def _clean(s):
    return re.sub(r"^[\s\"'“”«»‘’:,.;-]+|[\s\"'“”«»‘’:,.;!?-]+$", "", str(s or "")).strip()


def _line_at(at, note, turns):
    """(the text of the line named by 'm:ss' near the note - same speaker - and its time), else the note's own line."""
    line = (note.get("payload") or {}).get("line") or ""
    if at in (None, ""):
        return line, None
    try:
        p = [int(x) for x in str(at).strip().split(":")]
        sec = p[-1] + 60 * p[-2] + (3600 * p[-3] if len(p) == 3 else 0)
    except (ValueError, IndexError):
        return line, None
    who = note.get("turn_who") or "Medi"
    c = sorted((abs(u["t"] - sec), u) for u in (turns or []) if u["who"] == who and abs(u["t"] - sec) <= 1.5) if turns else []
    if not c:
        return line, None
    return c[0][1]["text"], c[0][1]["t"]


def use_at(note, said):
    """The grammar use the use-counter scored on this line (or the joined sentence) whose words hold `said`; None if none."""
    U = (J(os.path.join(REPO, "docs", "data", "grammar-usage.json"), {}) or {}).get("uses") or {}
    t0 = float(note.get("turn_t") or 0)
    t1 = float((note.get("payload") or {}).get("turn_end") or t0)
    n = _norm(said)
    for b, lst in U.items():
        for x in lst or []:
            if x.get("date") == str(note.get("lesson_date")) and t0 - 1 <= float(x.get("t") or -9) <= t1 + 1 and n and (n in _norm(x.get("said")) or n in _norm(x.get("hit")) or _sim(said, x.get("hit")) >= 0.6):
                return {"bucket": b, "said": x.get("hit") or x.get("said"), "t": x.get("t")}
    return None


def items_from_ai(ans, note, turns=None):
    """The model's JSON -> rows the builders already know (mirrors docs/js/correction-parse.js fromAI)."""
    line, who = (note.get("payload") or {}).get("line") or "", note.get("turn_who") or "Medi"
    if turns is None:
        turns = lesson_turns(note.get("lesson_date"))
    out = []
    for a in (ans or {}).get("items") or []:
        if not isinstance(a, dict):
            continue
        k = a.get("kind")
        if k == "speaker" and a.get("who") in ("Amal", "Medi"):
            out.append(("speaker", None, {"who": a["who"]}))
        elif k == "time":
            t = a.get("t")
            if isinstance(t, str) and re.match(r"^(?:\d+:)?\d{1,2}:\d{2}$", t.strip()):
                p = [int(x) for x in t.strip().split(":")]
                t = p[-1] + 60 * p[-2] + (3600 * p[-3] if len(p) == 3 else 0)
            if isinstance(t, (int, float)) and t >= 0:
                out.append(("time", None, {"t": float(t)}))
        elif k == "missing" and _clean(a.get("word")):
            out.append(("missing", None, {"heard": _clean(a["word"])}))
        elif k == "text" and _clean(a.get("engine_wrote")) and _clean(a.get("heard")):
            # PR-22: "at" names the line it changes (his sentence is split over short lines); the words must stand on it
            tl, at = _line_at(a.get("at"), note, turns)
            ew = _clean(a["engine_wrote"])
            hit = ew if ew in tl else (in_line(ew, tl) if len(ew.split()) == 1 else None)
            if hit:
                out.append(("text", {"word": hit}, {"engine_wrote": hit, "heard": _clean(a["heard"]), "from": "ai", **({"at": at} if at is not None else {})}))
        elif k == "credit" and _clean(a.get("word")) and who == "Medi":
            # WS-29: "should count" = a confirming row (the word stays as it is) that asks for the credit
            w = _clean(a["word"])
            short = re.sub(r"[.…,،؟?!:;]+", " ", line).split()
            hit = in_line(w, line) or (" ".join(short) if 0 < len(short) <= 4 else None)   # "Merhaba" for the line مرحبا.
            if not hit:
                continue
            out.append(("text", {"word": hit}, {"engine_wrote": hit, "heard": hit, "credit": "independent", "from": "ai"}))
        elif k == "not-use" and _clean(a.get("said")) and who == "Medi":
            u = use_at(note, _clean(a["said"]))
            if u:
                out.append(("not-use", {"rule": u["bucket"], "said": u["said"], "t": u["t"]}, {"reason": "asking", "from": "ai"}))
        elif k == "add" and _clean(a.get("said")) and who == "Medi":
            kk = "grammar" if a.get("k") == "grammar" else "vocab"
            out.append(("add", {"k": kk, "said": _clean(a["said"])}, {"k": kk, "wrong": _clean(a["said"]), "right": _clean(a.get("right")) or None}))
    return out


def claude_read(note, runner=None, log=print, spend=None):
    """ONE Haiku read of a note's raw words through `claude -p` (the repo's Claude path, scripts/track.py logs the run:
    model, tokens, cost). runner(prompt) -> stdout is injectable for tests. Returns the parsed JSON dict or None."""
    p = note.get("payload") or {}
    prompt = fill(note.get("turn_who") or "Medi", note.get("turn_t"), p.get("line") or "", p.get("raw") or note.get("note") or "",
                  context_lines(note))
    cmd = [CLAUDE, "-p", prompt, "--output-format", "json", "--model", MODEL]
    with track.run("correction_parse.read_note", str(note.get("lesson_date")), kind="inference", provider="anthropic",
                   request_model=MODEL, prompt_file="scripts/correction_parse_prompt.md",
                   prompt_sha=track.sha256_text(prompt_text()),
                   params={"note_id": note.get("id"), "prompt_arg_sha": track.sha256_text(prompt)}) as run:
        try:
            if runner:
                stdout = runner(prompt)
            else:
                r = subprocess.run(cmd, cwd=REPO, capture_output=True, text=True, encoding="utf-8", timeout=180)
                stdout = r.stdout
                if r.returncode:
                    run.set(status="error", error_type="exit_%d" % r.returncode)
                    log("correction_parse: claude exit %d: %s" % (r.returncode, (r.stderr or "")[-200:]))
                    return None
        except Exception as e:  # noqa: BLE001
            run.set(status="error", error_type=type(e).__name__)
            log("correction_parse: claude failed: %s" % type(e).__name__)
            return None
        parsed = track.parse_claude_output(stdout)
        run.claude(parsed)
        if parsed.get("cost_usd") is not None:
            try:
                if spend is None:
                    import pipeline_ext as PE
                    spend = PE.spend
                spend("anthropic", float(parsed["cost_usd"]), "parse-correction note %s (%s)" % (str(note.get("id"))[:8], MODEL))
            except Exception:  # noqa: BLE001
                pass
        txt = parsed.get("text") or ""
        m = re.search(r"\{[\s\S]*\}", txt)
        if not m:
            run.set(status="empty_output")
            return None
        try:
            return json.loads(m.group(0))
        except Exception:  # noqa: BLE001
            run.set(status="empty_output")
            return None


def rows_from_items(note, items, now=None):
    now = now or dt.datetime.now(dt.timezone.utc)
    rows = []
    p = note.get("payload") or {}
    for kind, target, payload in items:
        at = payload.pop("at", None)                       # PR-22: the row goes on the line it changes
        rows.append({"id": str(uuid.uuid4()), "lesson_date": str(note["lesson_date"]), "turn_t": at if at is not None else note["turn_t"], "turn_who": note.get("turn_who") or "Medi",
                     "kind": kind, "target": target, "payload": dict(payload, turn_end=p.get("turn_end"), line=p.get("line"), raw=p.get("raw") or note.get("note"), parsed_from=note["id"]),
                     "note": note.get("note"), "ts": now.isoformat(timespec="milliseconds").replace("+00:00", "Z"), "tz_offset_min": 0})
    return rows


def done_marker(note, now=None):
    """A 'note' child of the note: marks it read (nothing came of it, or the children are above) so it is never re-read."""
    now = now or dt.datetime.now(dt.timezone.utc)
    p = note.get("payload") or {}
    return {"id": str(uuid.uuid4()), "lesson_date": str(note["lesson_date"]), "turn_t": note["turn_t"], "turn_who": note.get("turn_who") or "Medi",
            "kind": "note", "target": None, "payload": {"raw": p.get("raw") or note.get("note"), "parsed_from": note["id"], "read": "ai", "line": p.get("line")},
            "note": None, "ts": now.isoformat(timespec="milliseconds").replace("+00:00", "Z"), "tz_offset_min": 0}


def unread_notes(rows):
    """Effective 'note' rows the page saved (no parsed_from) that no child row points at yet."""
    import medi_corrections as MC
    eff = MC.effective(rows)
    read = {(r.get("payload") or {}).get("parsed_from") for r in eff}
    return [r for r in eff if r.get("kind") == "note" and not (r.get("payload") or {}).get("parsed_from") and r["id"] not in read
            and ((r.get("payload") or {}).get("raw") or r.get("note"))]


def read_notes(rows=None, insert=None, runner=None, log=print, limit=MAX_NOTES_PER_RUN, spend=None):
    """-> {"read": n, "rows": [new rows]}; insert(rows) writes them (default: the table with the service key, then the mirror)."""
    import medi_corrections as MC
    rows = MC.all_rows() if rows is None else rows
    todo = unread_notes(rows)[:limit]
    out = {"read": 0, "rows": []}
    if not todo:
        return out
    for note in todo:
        ans = claude_read(note, runner=runner, log=log, spend=spend)
        new = rows_from_items(note, items_from_ai(ans, note)) if ans else []
        new.append(done_marker(note))
        out["rows"] += new
        out["read"] += 1
        log("correction_parse: note %s -> %s" % (str(note["id"])[:8], ", ".join(r["kind"] for r in new[:-1]) or "nothing (kept as a note)"))
    if out["rows"]:
        (insert or default_insert)(out["rows"])
    return out


def default_insert(rows):
    """The table (append-only, service key) first; then the mirror so this hour's build sees the rows."""
    import medi_corrections as MC
    try:
        import db
        db.rest("POST", "transcript_corrections", body=rows, prefer="resolution=ignore-duplicates,return=minimal")
    except Exception as e:  # noqa: BLE001
        print("correction_parse: table insert failed (%s); rows kept in the mirror only" % type(e).__name__)
    mirror = J(MC.OUT) or {"rows": []}
    have = {r["id"] for r in mirror.get("rows") or []}
    mirror["rows"] = sorted((mirror.get("rows") or []) + [r for r in rows if r["id"] not in have], key=lambda r: (str(r.get("ts")), r["id"]))
    W(MC.OUT, mirror)


# ------------------------------------------------------------------ the edge function's spend -> budget + run log

def mirror_spend(fetch=None, log=print, state_p=STATE_P, spend=None, log_run=None):
    """api_spend rows of the edge function (service anthropic, note 'parse-correction ...') newer than the last mirrored
    one -> one data/budget.json call + one run line each (same cost, the ledger's local clock), so the AI-paid-logged
    check matches them. Fail-open."""
    st = J(state_p) or {"last_ts": "", "mirrored": 0}
    try:
        if fetch is None:
            import db
            fetch = lambda: db.select("api_spend", {"service": "eq.anthropic", "note": "like.parse-correction*", "order": "ts.asc"})  # noqa: E731
        rows = fetch() or []
    except Exception as e:  # noqa: BLE001
        log("correction_parse: api_spend not reachable (%s)" % type(e).__name__)
        return {"mirrored": 0, "why": type(e).__name__}
    n = 0
    for r in sorted(rows, key=lambda x: str(x.get("ts"))):
        ts = str(r.get("ts") or "")
        if not ts or ts <= st["last_ts"] or not str(r.get("note") or "").startswith("parse-correction"):
            continue
        usd = float(r.get("usd") or 0)
        when = dt.datetime.fromisoformat(ts.replace("Z", "+00:00"))
        local = when.astimezone()
        (spend or _spend)("anthropic", usd, "%s (edge)" % r.get("note"), local)
        (log_run or track.log_run)("correction_parse.edge_read", None, kind="inference", provider="anthropic", request_model=MODEL,
                                   response_model=MODEL, cost_usd=round(usd, 6), cost_basis="estimate", prompt_file="scripts/correction_parse_prompt.md",
                                   started_at=when.isoformat().replace("+00:00", "Z"), params={"edge": "parse-correction", "api_spend_ts": ts})
        st["last_ts"] = ts
        n += 1
    st["mirrored"] = st.get("mirrored", 0) + n
    W(state_p, st)
    return {"mirrored": n}


def _spend(service, usd, what, when):
    """pipeline_ext.spend with the edge call's own time (its clock, made local like every other ledger line)."""
    import pipeline_ext as PE
    L = PE.ledger()
    L[service] = round(L.get(service, 0.0) + usd, 4)
    L["calls"].append({"t": when.replace(tzinfo=None).isoformat(timespec="seconds"), "service": service, "usd": round(usd, 4), "what": what})
    PE.LEDGER.parent.mkdir(parents=True, exist_ok=True)
    with open(PE.LEDGER, "w", encoding="utf-8") as f:
        f.write(json.dumps(L, ensure_ascii=False, indent=1))


def run(log=print):
    """What medi_corrections.py pull calls after the mirror: fail-open, one line each."""
    out = {}
    try:
        out["notes"] = read_notes(log=log)
    except Exception as e:  # noqa: BLE001
        out["notes"] = {"error": type(e).__name__}
        log("correction_parse: read-notes failed: %s %s" % (type(e).__name__, str(e)[:120]))
    try:
        out["spend"] = mirror_spend(log=log)
    except Exception as e:  # noqa: BLE001
        out["spend"] = {"error": type(e).__name__}
        log("correction_parse: mirror-spend failed: %s %s" % (type(e).__name__, str(e)[:120]))
    return out


def main(argv=None):
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["build-prompt", "read-notes", "mirror-spend", "run", "check"])
    a = ap.parse_args(argv)
    sys.stdout.reconfigure(encoding="utf-8")
    if a.cmd == "build-prompt":
        print("wrote", os.path.relpath(build_prompt_ts(), REPO))
        return 0
    if a.cmd == "check":
        ok = prompt_ts_fresh()
        print("prompt.ts %s" % ("matches scripts/correction_parse_prompt.md" if ok else "STALE: run `python scripts/correction_parse.py build-prompt`"))
        return 0 if ok else 1
    if a.cmd == "read-notes":
        print(json.dumps(read_notes(), ensure_ascii=False)[:800])
        return 0
    if a.cmd == "mirror-spend":
        print(json.dumps(mirror_spend()))
        return 0
    print(json.dumps(run(), ensure_ascii=False)[:800])
    return 0


if __name__ == "__main__":
    sys.exit(main())
