# -*- coding: utf-8 -*-
"""Medi's corrections on the Lessons page transcript (PR-15, Medi 2026-10-02: "i am going to make some corrections to the
transcript. try and make rule and patterns with my corrections.").

    python scripts/medi_corrections.py pull        # Supabase transcript_corrections -> data/lesson-work/medi-corrections.json
    python scripts/medi_corrections.py propose     # patterns behind each correction -> docs/data/correction-proposals.json
    python scripts/medi_corrections.py show        # the effective corrections, one line each

The page (docs/js/transcript-corrections.js) writes one row per correction (migration 022, append-only; Undo = a new row
with `undoes`). The effective set (rows not undone) enters UPSTREAM of every page, where the other human rulings enter:
  text / speaker / time / missing   transcript_fixes.load()  -> page turns + lesson_turns (TR-18 overlay)
  not-slip / was-wrong / classify / add   apply_rows() in full_audit_build.py  -> the reader rows every page reads
  not-use                           use_rulings() in detect_grammar_usage.load_rulings()
Precedence: Amal on Arabic correctness, Medi on everything else. A row Amal herself ruled (her tap, signal amal-ruling) is
never changed by his correction: it is listed in waiting_for_amal() for her Tutor hub. ANEES_CORRECTIONS=off = kill switch.
"""
import collections, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
OUT = os.path.join(REPO, "data", "lesson-work", "medi-corrections.json")
RULES_P = os.path.join(REPO, "data", "lesson-work", "correction-rules.json")
HAND_P = os.path.join(REPO, "data", "lesson-work", "medi-corrections-hand.json")   # his corrections typed in chat, same row shape
PROPOSALS_P = os.path.join(REPO, "docs", "data", "correction-proposals.json")
TEXT_KINDS = ("text", "speaker", "time", "missing")
ROW_KINDS = ("not-slip", "was-wrong", "classify", "add")
SIGNAL = "medi-correction"


def J(p, default=None):
    if not os.path.exists(p):
        return default
    with open(p, encoding="utf-8-sig") as f:
        return json.load(f)


def off():
    return os.environ.get("ANEES_CORRECTIONS", "").lower() == "off"


def sec(s):
    if s is None or s == "":
        return None
    if isinstance(s, (int, float)):
        return float(s)
    p = [float(x) for x in str(s).split(":")]
    return p[-1] + 60 * p[-2] + (3600 * p[0] if len(p) == 3 else 0)


def mmss(t):
    t = int(t or 0)
    return f"{t // 3600}:{t // 60 % 60:02d}:{t % 60:02d}" if t >= 3600 else f"{t // 60:02d}:{t % 60:02d}"


# ------------------------------------------------------------------ the log
def all_rows(path=OUT, hand=HAND_P):
    """The table mirror plus the corrections he gave in chat (hand file, same row shape, by: 'medi (chat)')."""
    return ((J(path) or {}).get("rows") or []) + (((J(hand) or {}).get("rows") or []) if hand else [])


def effective(rows=None):
    """Rows not undone, oldest first; an undo of an undo puts the row back. Rule answers are kept as rows too."""
    rows = all_rows() if rows is None else rows
    rows = sorted(rows, key=lambda r: (str(r.get("ts")), str(r.get("created_at") or ""), r["id"]))
    undone = set()
    for r in rows:
        if r.get("kind") == "undo" and r.get("undoes"):
            if r["undoes"] in undone:
                undone.discard(r["undoes"])
            else:
                undone.add(r["undoes"])
    # an undo row that was itself undone no longer undoes its target
    live_undo = {r["id"] for r in rows if r.get("kind") == "undo"} - undone
    gone = {r["undoes"] for r in rows if r.get("kind") == "undo" and r["id"] in live_undo}
    return [r for r in rows if r.get("kind") != "undo" and r["id"] not in gone]


def pull(path=OUT):
    """Mirror the table (read-only, anon key). None = the table does not exist yet (migration 022 not applied)."""
    import pull_decisions as PD
    rows = PD.http_fetch("transcript_corrections", order="ts.asc,id.asc")
    if rows is None:
        return None
    old = {r["id"]: r for r in all_rows(path, hand=None)}
    for r in rows:
        old[r["id"]] = r
    data = {"about": "Mirror of Supabase transcript_corrections (migration 022): Medi's corrections on the Lessons page "
                     "transcript. Generated by scripts/medi_corrections.py pull; never edited by hand. Undo = a row with "
                     "undoes; the builders apply medi_corrections.effective().",
            "rows": sorted(old.values(), key=lambda r: (str(r.get("ts")), r["id"]))}
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, ensure_ascii=False, indent=1)
        f.write("\n")
    return data


# ------------------------------------------------------------------ entry points for the builders
def text_rows(rows=None):
    """Heard-word overlay rows (transcript_fixes.json shape) from his text / speaker / time / missing corrections."""
    if off():
        return []
    out = []
    for r in effective(rows):
        if r.get("kind") not in TEXT_KINDS:
            continue
        p = r.get("payload") or {}
        base = {"date": str(r["lesson_date"]), "t": float(r["turn_t"]), "who": r["turn_who"], "rule": "PR-15", "by": "medi",
                "on": str(r.get("ts"))[:10], "quote": r.get("note"), "correction": r["id"]}
        if r["kind"] in ("text", "missing") and p.get("engine_wrote") is not None and p.get("heard") is not None:
            out.append(dict(base, engine_wrote=p["engine_wrote"], heard=p["heard"]))
        elif r["kind"] == "speaker" and p.get("who") in ("Medi", "Amal"):
            out.append(dict(base, engine_wrote="", heard="", set_who=p["who"]))
        elif r["kind"] == "time" and isinstance(p.get("t"), (int, float)):
            out.append(dict(base, engine_wrote="", heard="", set_t=float(p["t"])))
    return out


def _class(kind):
    return "grammar" if str(kind or "").startswith("grammar") else "vocab" if str(kind or "").startswith("vocab") else None


def _piece(s):
    return re.sub(r"[\s.…,،؟?!:;\"“”()\-]+", "", str(s or "")).replace("أ", "ا").replace("إ", "ا").replace("ة", "ه")


def matches(row, c):
    """Is reader row `row` the item correction c is about? Same lesson, his line's time span (+-3 s), same kind and the
    same wrong piece or rule."""
    if str(row.get("date")) != str(c["lesson_date"]):
        return False
    tg, p = c.get("target") or {}, c.get("payload") or {}
    t = sec(row.get("t"))
    lo, hi = float(c["turn_t"]) - 3, float(p.get("turn_end") or c["turn_t"]) + 3
    if t is None or not (lo <= t <= hi):
        return False
    if tg.get("k") and _class(row.get("kind")) != tg["k"] and row.get("kind") != "rejected":
        return False
    w = _piece(tg.get("wrong") or tg.get("said"))
    if w and (_piece(row.get("wrong")) in w or w in _piece(row.get("wrong"))) and _piece(row.get("wrong")):
        return True
    return bool(tg.get("rule")) and row.get("bucket") == tg.get("rule")


def apply_rows(rows, corrections=None, quote_date=None):
    """full_audit_build: his not-slip / was-wrong / classify / add on the reader rows (every page reads them). Returns
    {"applied": [...], "unmatched": [...], "waiting_for_amal": [...]}. Nothing is deleted: a dropped row keeps its data
    with kind 'rejected' and his words."""
    rep = {"applied": [], "unmatched": [], "waiting_for_amal": []}
    if off():
        return rep
    for c in effective(corrections):
        k = c.get("kind")
        if k not in ROW_KINDS:
            continue
        p, tg = c.get("payload") or {}, c.get("target") or {}
        who = "Medi %s" % str(c.get("ts"))[:10]
        words = (": " + c["note"]) if c.get("note") else ""
        if k == "add" or (k == "was-wrong" and not any(matches(r, c) for r in rows if r.get("kind") != "rejected")):
            g = (p.get("k") or tg.get("k")) == "grammar"
            new = {"id": "MC-" + c["id"][:8], "date": str(c["lesson_date"]), "t": mmss(c["turn_t"]), "t_amal": p.get("t_amal"),
                   "medi_said": p.get("line"), "amal_said": p.get("amal_said"), "wrong": p.get("wrong") or tg.get("said") or tg.get("word"),
                   "right": p.get("right") or "", "kind": "grammar" if g else "vocab-A", "bucket": p.get("rule") or tg.get("rule") if g else None,
                   "tier": None if g else 1, "mode": "speaking", "signal": SIGNAL, "confidence": "high", "source": "medi-correction",
                   "correction": c["id"], "agreed_by": "medi-correction", "why": "%s marked it a mistake%s" % (who, words)}
            if k == "was-wrong" and tg.get("k") == "vocab":
                new["wrong"] = tg.get("word") or tg.get("said")
            rows.append(new)
            rep["applied"].append(c["id"])
            continue
        hit = [r for r in rows if matches(r, c) and (r.get("kind") != "rejected" or k == "was-wrong")]
        if not hit:
            rep["unmatched"].append(c["id"])
            continue
        for r in hit:
            if r.get("signal") == "amal-ruling":
                rep["waiting_for_amal"].append({"correction": c["id"], "row": r.get("uid") or r.get("id"), "kind": k})
                continue
            r.setdefault("medi_corrections", []).append(c["id"])
            if k == "not-slip":
                r["kind_before_rejection"] = r["kind"]
                r.update(kind="rejected", rejected_why="%s: not a mistake%s" % (who, words), rejected_rule="PR-15")
            elif k == "was-wrong":            # a row the readers dropped: he says it was a mistake
                r.update(kind=r.get("kind_before_rejection") or "vocab-A", confidence="high", signal=r.get("signal") or SIGNAL)
                r.pop("rejected_why", None)
            elif k == "classify":
                r["kind_before_medi"], r["bucket_before_medi"] = r.get("kind"), r.get("bucket")
                if p.get("to") == "vocab":
                    r.update(kind="vocab-A" if r.get("kind") in ("grammar", "vocab-A") else "vocab-B", bucket=None)
                else:
                    r.update(kind="grammar" if r.get("kind") in ("grammar", "vocab-A") else "grammar-B", bucket=p.get("rule"))
                if p.get("wrong"):
                    r["wrong_before_medi"], r["wrong"] = r.get("wrong"), p["wrong"]
                if p.get("right"):
                    r["right_before_medi"], r["right"] = r.get("right"), p["right"]
                r["why"] = "%s: %s%s. Readers wrote: %s" % (who, "a wrong word" if p.get("to") == "vocab" else "grammar " + str(p.get("rule")), words, r.get("why"))
        rep["applied"].append(c["id"])
    return rep


def use_rulings(corrections=None):
    """detect_grammar_usage.load_rulings: his 'not a use' on a ✓ grammar chip -> a ruled-out use row."""
    if off():
        return []
    out = []
    for c in effective(corrections):
        if c.get("kind") != "not-use":
            continue
        tg = c.get("target") or {}
        out.append({"date": str(c["lesson_date"]), "t": float(c["turn_t"]), "bucket": tg.get("rule"), "hit": tg.get("said"),
                    "why": "Medi %s: not a use%s" % (str(c.get("ts"))[:10], (": " + c["note"]) if c.get("note") else ""),
                    "ruling_by": "medi-correction", "rule": "PR-15", "correction": c["id"], "turn_end": (c.get("payload") or {}).get("turn_end")})
    return out


# ------------------------------------------------------------------ patterns -> proposed rules (S6)
def _lessons(repo=REPO):
    d = os.path.join(repo, "docs", "data", "lessons")
    for f in sorted(os.listdir(d)) if os.path.isdir(d) else []:
        if re.fullmatch(r"\d{4}-\d\d-\d\d\.json", f):
            yield f[:10], J(os.path.join(d, f))


def propose(corrections=None, repo=REPO):
    """One proposal per correction that has a general shape, with every other moment it would change. A proposal Medi
    already answered (kind rule-answer) carries his answer. Only shapes that are about the transcript or the app are ever
    applied on 'yes'; a shape about whether his Arabic was right is labelled for Amal."""
    eff = effective(corrections)
    answers = {r.get("proposal"): r for r in eff if r.get("kind") == "rule-answer"}
    lessons = list(_lessons(repo))
    out = []
    for c in eff:
        k, p, tg = c.get("kind"), c.get("payload") or {}, c.get("target") or {}
        pid = "P-" + c["id"][:8]
        if k == "text" and p.get("engine_wrote"):
            X, Y = p["engine_wrote"], p["heard"]
            hits = [{"date": d, "t": u["t"], "mmss": mmss(u["t"]), "line": u["text"]} for d, L in lessons for u in L.get("turns") or []
                    if u["who"] == c["turn_who"] and X in (u.get("engine") or u["text"])
                    and not (d == str(c["lesson_date"]) and abs(u["t"] - float(c["turn_t"])) <= 1)]
            out.append({"id": pid, "from": c["id"], "kind": "text", "owner": "medi",
                        "plain": "When the recording engine writes «%s» on %s line, you said «%s»." % (X, "your" if c["turn_who"] == "Medi" else "Amal's", Y),
                        "pattern": {"who": c["turn_who"], "engine_wrote": X, "heard": Y}, "moments": hits})
        elif k == "not-slip":
            sig = p.get("signal")
            hits = []
            A = J(os.path.join(repo, "data", "full-audit-2026-09-26.json")) or {}
            for r in (A.get("sweep_compat") or {}).get("rows", []) + (A.get("sweep_compat") or {}).get("vocab", []):
                if _piece(r.get("wrong")) and _piece(r.get("wrong")) == _piece(tg.get("wrong") or tg.get("said")) and r.get("signal") == sig \
                        and not (str(r.get("date")) == str(c["lesson_date"]) and abs((sec(r.get("t")) or 0) - float(c["turn_t"])) <= 4):
                    hits.append({"date": r["date"], "t": sec(r.get("t")), "mmss": r.get("t"), "line": r.get("medi_said")})
            out.append({"id": pid, "from": c["id"], "kind": "not-slip", "owner": "amal",
                        "plain": "«%s» with Amal's «%s» is not a mistake." % (tg.get("wrong") or tg.get("said"), sig or "reaction"),
                        "pattern": {"wrong": tg.get("wrong") or tg.get("said"), "signal": sig}, "moments": hits})
        elif k == "add" and (p.get("wrong") or tg.get("said")):
            W = p.get("wrong") or tg.get("said")
            hits = [{"date": d, "t": u["t"], "mmss": mmss(u["t"]), "line": u["text"]} for d, L in lessons for u in L.get("turns") or []
                    if u["who"] == "Medi" and W in u["text"] and not (d == str(c["lesson_date"]) and abs(u["t"] - float(c["turn_t"])) <= 1)]
            out.append({"id": pid, "from": c["id"], "kind": "add", "owner": "amal",
                        "plain": "You said «%s» for «%s» on other days too." % (W, p.get("right") or "?"), "pattern": {"wrong": W, "right": p.get("right")}, "moments": hits})
        else:
            continue
        a = answers.get(pid)
        if a:
            out[-1]["answer"] = {"answer": a.get("answer"), "at": a.get("ts"), "note": a.get("note")}
    return out


def write_proposals(repo=REPO):
    P = propose(repo=repo)
    with open(PROPOSALS_P if repo == REPO else os.path.join(repo, "docs", "data", "correction-proposals.json"), "w", encoding="utf-8", newline="\n") as f:
        json.dump({"about": "Rules proposed from Medi's transcript corrections (PR-15, scripts/medi_corrections.py propose). "
                            "owner medi = applied to every lesson on his yes; owner amal = an Arabic question, goes to her Tutor hub.",
                   "proposals": P}, f, ensure_ascii=False, indent=1)
        f.write("\n")
    # his yes on a transcript-shaped proposal becomes a standing rule, applied to every lesson (future ones too)
    rules = [{"id": "MC-%03d" % (i + 1), "proposal": x["id"], "from": x["from"], "kind": x["kind"], "plain": x["plain"],
              "pattern": x["pattern"], "quote": (x.get("answer") or {}).get("note"), "on": str((x.get("answer") or {}).get("at"))[:10], "rule": "PR-15"}
             for i, x in enumerate(p for p in P if p["owner"] == "medi" and (p.get("answer") or {}).get("answer") == "yes")]
    with open(RULES_P if repo == REPO else os.path.join(repo, "data", "lesson-work", "correction-rules.json"), "w", encoding="utf-8", newline="\n") as f:
        json.dump({"about": "Medi's yes to a proposed rule (PR-15). Generated from his answers; applied by transcript_fixes.load "
                            "to every lesson.", "rules": rules}, f, ensure_ascii=False, indent=1)
        f.write("\n")
    return P, rules


def rule_text_rows(repo=REPO):
    """Standing text rules (his yes): every line of that speaker where the engine wrote X reads Y, in every lesson."""
    if off():
        return []
    R = (J(RULES_P if repo == REPO else os.path.join(repo, "data", "lesson-work", "correction-rules.json")) or {}).get("rules") or []
    return [{"pattern": True, "who": r["pattern"]["who"], "engine_wrote": r["pattern"]["engine_wrote"], "heard": r["pattern"]["heard"],
             "rule": r["id"], "by": "medi"} for r in R if r.get("kind") == "text"]


def main(argv=None):
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["pull", "propose", "show"])
    a = ap.parse_args(argv)
    sys.stdout.reconfigure(encoding="utf-8")
    if a.cmd == "pull":
        d = pull()
        print("transcript_corrections: table not set up yet (migration 022)" if d is None else "pulled %d rows" % len(d["rows"]))
        return 0
    if a.cmd == "propose":
        P, R = write_proposals()
        print("%d proposals, %d standing rules" % (len(P), len(R)))
        return 0
    for c in effective():
        print(c["lesson_date"], mmss(c["turn_t"]), c["turn_who"], c["kind"], json.dumps(c.get("payload"), ensure_ascii=False), c.get("note") or "")
    return 0


if __name__ == "__main__":
    sys.exit(main())
