"""Writes docs/js/config.js (Supabase URL + anon key; the anon key is public by design, RLS protects the rows)."""
import io, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
import anees_env as E
p = Path(__file__).resolve().parent.parent / 'docs' / 'js' / 'config.js'
p.write_text(f"// Public config (the anon key is public by design; RLS protects the data). Generated by scripts/write_config.py\nwindow.ANEES = {{ url: '{E.SUPABASE_URL}', anon: '{E.ANON_KEY}', pages: 'https://thenatanzi.github.io/anees/' }};\n", encoding='utf-8')
print('wrote', p)
